---
title: "Welcome Back"
linktitle: "0: Introduction"
date: "2024-01-08"
read_date: "2024-01-08"
draft: false
lastmod: "`r Sys.Date()`"
menu:
  content:
    parent: Course content
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: false
slides: "00-Introduction"

---

## Slides

Throughout the course, class slides will be posted on this course website. Many are posted already, but *do not rely on old versions*. I cannot emphasize this enough. Use the buttons below to open the slides either as an interactive website or as a static PDF. You can also click in the slides below and navigate through them with your left and right arrow keys.

Please note: you may experience some performance issues when opening the PDF file with Preview; Adobe Acrobat does not have these problems. You can always just open the slides in another window (and they will perform perfectly). But the .pdf versions have some hiccups when you try to open them in Preview. I dunno. 

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R/slide_tabs.R"))
source(here::here("R/pdfize.R"))
sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Top", "Cover", TRUE,
  "Key Info", "section2", FALSE,
 )
slide_tabs(sections, "/slides/00-Introduction.html")
pdfize(here::here("static/slides/00-Introduction.html"))
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands; on some slides, this might give helpful hints! But probably not.
:::
