---
title: "Choice under Uncertainty: The Standard Model"
linktitle: "1a: Uncertainty -- The Standard Model"
date: "2023-01-12"
read_date: "2023-01-12"
draft: false
lastmod: "`r Sys.Date()`"
menu:
  content:
    parent: Course content
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: false
slides: "01-ExpectedUtility"

---
## A Note on Old Materials

The course website has some older notes posted. It is not recommended that you use these. When in doubt, check the date on the top of the page to verify you're viewing current materials. 

## Slides

Every single set of class slides can be found on this course website. Use the buttons below to open the slides either as an interactive website or as a static PDF. You can also click in the slides below and navigate through them with your left and right arrow keys.

Please note: you may experience some performance issues when opening the PDF file with Preview; Adobe Acrobat does not have these problems.

### Introduction to Choice under Uncertainty

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R/slide_tabs.R"))
source(here::here("R/pdfize.R"))
sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Top", "Cover", TRUE,
  "Expected Value", "section4", FALSE,
  "Expected Utility", "section6", FALSE,
  "Applications", "section8", FALSE,
 )
slide_tabs(sections, "/slides/01-ExpectedUtility.html")
pdfize(here::here("static/slides/01-ExpectedUtility.html"))
```


:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands; on some slides, this might give helpful hints!
:::
