---
title: "Choice under Uncertainty: Prospect Theory"
linktitle: "1c: Prospect Theory"
date: "2023-01-24"
read_date: "2023-01-24"
draft: false
lastmod: "`r Sys.Date()`"
menu:
  content:
    parent: Course content
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: false
slides: "03-ProspectTheory"

---

## A (Gentle) Reminder

Problem sets are your main way of learning the material for this course. You ought to be engaging with them early and often. They don't take a collosal amount of time, but they can be a real bear if you try to do them at the last minute. (And then you won't learn things very well, if at all.)

## Slides

Use the buttons below to open the slides either as an interactive website or as a static PDF. You can also click in the slides below and navigate through them with your left and right arrow keys.

Please note: you may experience some performance issues when opening the PDF file with Preview; Adobe Acrobat does not have these problems.

### Prospect Theory:

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R/slide_tabs.R"))
source(here::here("R/pdfize.R"))
sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Top", "Cover", TRUE,
 )
slide_tabs(sections, "/slides/03-ProspectTheory.html")
pdfize(here::here("static/slides/03-ProspectTheory.html"))
```


:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands; on some slides, this might give helpful hints!
:::
