---
title: "Choice over Time: All Notes"
linktitle: "2: Choice over Time"
date: "2021-09-07"
read_date: "2021-09-07"
draft: false
lastmod: "`r Sys.Date()`"
menu:
  content:
    parent: Course content
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: false


---

## Slides

Due to slide rendering issues, all PDFs will be hosted below for the time being.

Click this first icon to download the first batch of slides (discussing interest rates and present discounted value): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4a.pdf).

Click this second icon to download the second batch of slides (discussing the "standard model" aka exponential discounting): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4b.pdf).

Click this third icon to download the third batch of slides (discussing evidence contradicting the standard model): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4c.pdf).

Click this fourth icon to download the fourth batch of slides (discussing an alternative model---"present bias"): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4d.pdf).

Click this fifth icon to download the fifth batch of slides (discussing applications of present bias): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4e.pdf).

Click this sixth icon to download the sixth batch of slides (discussing more applications of present bias): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4e2.pdf).

Click this seventh icon to download the seventh batch of slides (discussing more applications of present bias): [<i class="fas fa-file-download"></i>](/ps/EC404_Lecture4f.pdf).
