main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: '<i class="fab fa-slack"></i>'
    url: "https://join.slack.com/t/ec404/shared_invite/zt-11h2bhvuu-nvnLANd0u_VZO7PJOa55TQ"
    weight: 5

content:
  - name: Course content
    weight: 2
assignments:
  - name: Assignments
    weight: 2
