main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: '<i class="fab fa-slack"></i>'
    url: "https://join.slack.com/t/slack-nzx9830/shared_invite/zt-v1w19zom-xpFAQGba3R25MYQzVViHqQ"
    weight: 5

content:
  - name: Course content
    weight: 2
assignments:
  - name: Assignments
    weight: 2
