main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4


content:
  - name: Course content
    weight: 2
assignments:
  - name: Assignments
    weight: 2
