---
title: Assignments and Evaluations
menu:
  assignment:
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: false
---

## In-Class Activities

To encourage you to actively engage with the course content, I will assign short (one-paragraph) writings, in-class questions, or alternative assignments each week. These will count toward your participation grade. Accordingly, they will **only be available in class**. I will not repeat the assignments and some will actually require you to be physically in the class.

The TA will grade these mini-exercises using a very simple system:

- ✔+: (*115% in gradebook*) Work shows phenomenal thought and engagement with the course content. We will not assign these often.
- ✔: (*100% in gradebook*) Work is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- ✔−: (*50% in gradebook*) Work is hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. We will hopefully not assign these often.

There is an implicit 0 above for work that is not turned in. Notice that this is essentially a pass/fail or completion-based system. We're not grading your writing ability; we're not counting the exact number of words you're writing; and we're not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. We are looking for thoughtful engagement. Read the material, engage with the work and you'll get a ✓.

## Assignments

Assignments form your main learning tool. Since there is no textbook, you should plan on spending quite a bit of time on each assignment. Overall, assignments will be graded the same check system:

- ✔+: (*115% in gradebook*) Exercises are complete. Every task was attempted and answered, and most answers are correct. Work on the final problem shows creativity or is otherwise exceptional. We will not assign these often.
- ✔: (*100% in gradebook*) Exercises are complete and many answers are correct. This is the expected level of performance.
- ✔−: (*50% in gradebook*) Exercises are less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. We will hopefully not assign these often, but subpar work can expect a ✔−.

There is an implicit 0 for any assignment not turned in on time. If you have only partial work, then turn that in for some credit. We are not checking each line and we do not expect perfection; rather, the assignments are your main tool to *learn*.  Also note that a ✓ does not require 100% success. You will sometimes get stuck with tricky algebra that you can't solve, or the demands of pandemic living might occasionally become overwhelming. We are looking for good faith effort. Try hard, engage with the task, and you'll get a ✓.

You may work together on the assignments, but you must turn in your own answers. You will turn these assignments in class or via D2L (if pandemic living requires).

## Paper

To meet the MSU Tier II Writing requirement, you will complete a paper near the end of the course.

This paper is intended to be minimally intrusive. It will be graded using a check system as well:

- ✔+: (*55 points (≈115%) in gradebook*) Project is phenomenally well-thought-out and uses advanced techniques. The project discusses some important story that is not readily obvious. I will not assign these often.
- ✔: (*50 points (100%) in gradebook*) Project is fine, answers a question clearly, and discusses concepts from the course. This is the expected level of performance.
- ✔−: (*25 points (50%) in gradebook*) Project is missing large components, is poorly written, does not answer a relevant question, and/or states falsehoods. This indicates that you need to improve next time. If you receive this grade, you may revise your paper.
